### ISSUE TITLE
컨벤션 정리

### ISSUE THREAD

**Issue by DaHoon06** [DaHoon06/Dotto#101]
## 1. CSS Naming Convention

- BEM 표기법 (Block__Element--Modifier)

## 2. Git Convention 

- feat : 새로운 기능 추가 
- fix : 버그 픽스 
- docs : 문서 수정
- design : CSS 추가 및 수정
- refactor : 코드 리펙토링
- test : 테스트 코드 추가
- chore : 위에 해당하지 않는 모든 변경,
- init: 라이브러리 설치하는 경우
- close: 이슈 종료 키워드

**Comment by cockyb** [comment]
BEM 표기법은 css in js, scss, module css와 같은 style 라이브러리들이 주류를 이루면서 퇴색된 방법론이긴합니다.

* css in js
=> <Header >
         <Logo />
</Header>
컴포넌트의 네이밍이 엘리먼트를 직관적으로 표현합니다.

* scss
.header {
  & .logo {
   }
}
nesting을 통해 엘리먼트간의 관계를 표현합니다

* module css
import styles from 'Header.mdoule.css';
<div className={styles.header} >...
마찬가지로 nesting, 모듈 형태로 스타일코드를 작성하여 conflict를 회피합니다.

style library를 어떤걸 사용하게될진 모르겠지만
기존 vue로 작성된 프로젝트처럼 pure css를 사용한다면 유의미한 컨벤션이라고 생각합니다.

사용하게될 프레임워크, 라이브러리도 이슈로 등록하고 의견교환하면서 얘기나눠봐요

**Comment by DaHoon06** [comment]
안녕하세요.

BEM의 경우 scss 를 다뤄보면서 깔끔한거 같아 기록해봤습니다!!

현재로써 정해진게 없기 때문에 괜찮은 방향 있으시면 의견 부탁드려요..!!! 😄

**Comment by cockyb** [comment]
scss로 가게된다면 BEM을 적용해보면 좋겠네요

**Comment by cockyb** [comment]
++ 폴더 네이밍 컨벤션
[링크](https://stackoverflow.com/a/44882336)참조하여 folder naming은 kebab-case 사용하고 있습니다

파일명은
컴포넌트 - PascalCase
그외 - kebab-case

**Comment by DaHoon06** [comment]
넵 확인했습니다!

**Comment by DaHoon06** [comment]
@cockyb 

파일이나 디렉토리 구조나 각자 작업을 하다 보니까 조금씩 달라지는 부분이 있는 것 같은데 이번 주내에 (날짜 정해서) 작업물을  한번 합치고 작업을 진행하는게 어떨까요??

**Comment by cockyb** [comment]
@DaHoon06  네 좋습니다 수요일 괜찮으실까요?

**Comment by DaHoon06** [comment]
수요일에 작업을 못할 것 같아서 그런데 목요일에 올려도 괜찮을까요????

**Comment by cockyb** [comment]
넵 알겠습니다

**Comment by cockyb** [comment]
BEM + pure css(scss)로 진행하고 있어서, 협업시에는 엘리먼트 클래스 네이밍이 겹칠일이 없은 것 같긴한데,
common component 구성하면서 가져간 범용적인 클래스 네임들이 라이브러리 쪽 className 컨플릭트나고 있는상황입니다
클래스네임을 변경하면 되긴하나 길게봤을 때 늦기전에 css(scss) module로 전환하면 어떨까합니다.

추가로 css에서 
.box {
  & .box__content {
     & .box_icon {
     }
  }
}
이런식으로 nesting 해두었다가 파일을 분리하려고 할 때 단순 cut & paste만 필요한게 아니라 & 기호도 지워야하니 손이 더가는 것 같습니다.

**Comment by DaHoon06** [comment]
아 겹칠꺼라고는 생각을 못했네요 말씀해주시댄로 더 하기 전에 수정하는게 좋을 것 같습니다...
