### ISSUE TITLE
기술 스택 선정

### ISSUE THREAD

**Issue by cockyb** [DaHoon06/Dotto#102]
### 메인 라이브러리
- [x] React
- [ ] Vue

### 언어
- [X] Typescript

### 프레임 워크 & 번들러 
- [ ] #103
* SSR 지원 
* 러닝커브 꽤 있음 
- [ ] [Vite](https://vitejs-kr.github.io/)
* 빌드속도 빠름
- [x] [Create React App](https://create-react-app.dev/) (webpack)
* 대중적임

### 스타일 라이브러리
- [ ] pure css
* 기존 프로젝트 작성된내용 그대로 복붙하여 살릴 수 있음
- [x] [scss(sass)](https://sass-lang.com/)
* 기존 프로젝트 코드베이스 바탕으로 쉽게 migration 가능함, module scss도 마찬가지
- [ ] [emotion](https://emotion.sh/docs/introduction) or [styled-component](https://styled-components.com/)
* 대중적인 css in js
- [ ] [stiches](https://stitches.dev/)
* 2세대 css in js 
* zero runtime
- [ ] [tailwind](https://tailwindcss.com/)
* 커뮤니티에서도 호불호가 많이 갈림
* css framework 유틸리티 클래스명을 배워야하는 리스크있음

### 상태관리
- [ ] [redux(rtk)](https://ko.redux.js.org/introduction/getting-started/)
* 많은 보일러플레이트 코드 
* 단독으로 쓰인다면 서버 상태 관리 직접해줘야함
- [ ] [recoil](https://recoiljs.org/ko/)
* 작은단위의 상태들을 관리하기 좋음
* 규모가 커졌을 때 관리하기 힘듬
* 단독으로 쓰인다면 서버 상태 관리 직접해줘야함
- [x] [zustand](https://docs.pmnd.rs/zustand/getting-started/introduction)
* 리코일과 비슷
* 단독으로 쓰인다면 서버 상태 관리 직접해줘야함
- [x] [react-query](https://tanstack.com/query/v4/docs/overview) (서버상태관리)
* 문서 불친절
* react-query + 클라이언트 상태관리 도구 <= 최근 가장 많이쓰는듯함
- [ ] [swr](https://swr.vercel.app/ko) (서버상태관리)
* react-query와 차이를 잘 모르겠음 무튼 react-query가 더많이 쓰임

### 배포
- [x] [netlify](https://docs.netlify.com/site-deploys/post-processing/prerendering/)
* prerendering으로 seo대응 가능
- [ ] [aws s3](https://aws.amazon.com/ko/?nc2=h_lg)
* 백엔드가 어디에 배포될지 모르나 연계 서비스가 많음(route54, cdn ...)
* seo 대응하려면 headless browser용도로 단일서버 필요함

### 추가적인 라이브러리 선택할 때 참고할만한 곳
[npm trend](https://npmtrends.com/)
[js coach](https://js.coach/)

**Comment by DaHoon06** [comment]
먼저 저는 실무에서 Vue 프로젝트만 진행을 해봐서 React 에서의 상태 관리를 어떤 식으로 하는게 좋을지 판단이 안되서 이 부분은 경준님이 선택해 주시면 어떨까 싶습니다..

스타일 라이브러리는 현재 scss 를 사용해보고 있는데 tailwind도 사용해보고 싶기도 합니다.

백엔드는 aws에 올릴 예정이라 s3를 생각하고 있었는데 seo 대응도 필요하군요.. 이 부분도 생각해 볼께요... 정리 감사합니다

**Comment by cockyb** [comment]
zustand로 클라이언트 상태를 관리하고 서버상태 관리는 react-query를 사용해보면 좋을것 같습니다. 

style라이브러리는 그럼 기존 코드 베이스를 위해 scss 사용하면 괜찮을까요?
tailwind는 [여기](https://www.aleksandrhovhannisyan.com/blog/why-i-dont-like-tailwind-css/)내용 처럼 의견이 많이 갈리기도하고
저도 tailwind 좋아하지만 쓰다보니 단점이 좀 보이더라구요. 보완하고 싶어서 tailwind를 쓴다면 [twin.macro](https://github.com/ben-rogerson/twin.macro)같은 css in js + tailwind를 써볼 게획이였는데, 다훈님 입장에서는 css in js + css framework 두개를 봐야하는 입장일 것 같아 scss로 가면 좋을 것 같습니다. (스타일 라이브러리에 과도하게 리소스를 투자하는 것 보다 상태관리나 리액트 기본에 더 투자하면 이직에도 좋을 것 같습니다.)

배포는 차차결정해도 좋을 것 같습니다

**Comment by DaHoon06** [comment]
넵넵 저는 좋아요!!!
그럼 상태 관리는 저렇게 하고 스타일은 scss로 하고..
Next였다가 CRA 으로 변경되었던데 이유가 있을까요?
저는 Next로 진행했으면 합니다.!!  
(SSR을 써보고 싶은 개인적인 욕심입니다..ㅎㅎㅎ 러닝 커브가 문제가 된다면 그건 제가 감수 해야 할 몫 이니깐요)
