### ISSUE TITLE
브랜치 전략

### ISSUE THREAD

**Issue by DaHoon06** [DaHoon06/Dotto#119]
main
|
ㄴ dev
ㄴ frontend
|       ㄴ /기능??
|       ㄴ /기능??
|
ㄴ backend
        ㄴ /기능??
        ㄴ /기능??

**Comment by DaHoon06** [comment]
기존에는 frontend/본인이니셜/기능 별로 관리하고

백엔드와 프론트엔드 코드를 병합할 때 dev 브랜치에다가 병합하고 에러 해결 후 main 에 올렸는데 이 방식 그대로 유지할까요?

**Comment by DaHoon06** [comment]
@cockyb 홈 레이아웃 작업은 migration/react 브랜치가 있길래 거기서 가져와서 작업 중입니다.

**Comment by cockyb** [comment]
dev브랜치가 하나있으면 좋을 것 같아요 deploy마다 dev브랜치는 main에 병합하도록 하죠

**Comment by jaeeey01** [comment]
이전 사용했던 브랜치는 한번 정리하는게 좋을 것 같네요 
지금은 좀 지저분한 감도 있어서 ..

**Comment by DaHoon06** [comment]
이전 브랜치 한번 정리하겠습니다!! 백엔드 쪽은 재현이형이 한번 해주세요!

**Comment by jaeeey01** [comment]
백엔드 브랜치 정리 완료
