### ISSUE TITLE
proxy set-up

### ISSUE THREAD

**Issue by DaHoon06** [DaHoon06/Dotto#155]

**Comment by DaHoon06** [comment]
@cockyb 

netify 배포하면서 같이 proxy 셋업하고 있는데 혹시나 작업하실까봐 issue 등록합니다!!
셋업하고 PR 보낼께요

**Comment by cockyb** [comment]
proxy가 cors우회 용도인가요?
 로컬에서 개발중에 편의(cors)를 위해 proxy를 이용하는건 이해하고 있는데 실제 배포환경에서 프록시를 쓰면 좋은점이 있나요?

**Comment by DaHoon06** [comment]
넵 proxy 셋업한게 로컬에서 api 테스트 해볼려고 올린거였습니다.
