### ISSUE TITLE
게시글 불러올 때 체크 사항

### ISSUE THREAD

**Issue by DaHoon06** [DaHoon06/Dotto#48]
###  - CHECK!! -
**1. 메인 화면은 최근 기준 8개의 게시물이 필요**
**2. 각 메인 게시글 디자인 기준 16개의 게시물 이후 스크롤 방식으로 페이징 처리**

___

홈 화면에서 게시글이 최대 8개만 보여지면 되어 처음 생각은 limit을 8만 줘서 호출할 생각 이였습니다.

근데 이런 방법을 하게 되면 전체 보기로 이동 시에도 8개의 게시물만 보여지게 됩니다.

그래서 다른 방안으로  **API를 2개**를 만들어서 **홈 화면에서 호출할 때는 limit 8** 로
**각 게시물에서 호출할 때는 limit 16** 을 보내주는 방식으로 하면 어떨까 합니다.

**Comment by yjh920127** [comment]
회의 결과 
게시판 목록 조회시 프론트에서 limit 값을 포함하여 요청을 하면 해당하는 만큼의 데이터만 백에서 전달하도록 함

**Comment by DaHoon06** [comment]
그럼 프론트에서 limit 라는 변수명으로 백엔드로 넘기겠습니다!!!
