### ISSUE TITLE
프론트 충돌처리 관련

### ISSUE THREAD

**Issue by COSMOS98** [DaHoon06/Dotto#61]
파일명
PolicyComponent.vue

<template>
  <section id="policy-container">

    <article>
      <div class="policy-items">
        <div>
          <input type="checkbox" id="check" @change="[handleClickAllCheckBox(), btnActive()]" v-model="allCheckItems" />
          <label for="check"></label>
        </div>
        <div id="policy-title" class="policy-title-test">전체 동의 합니다.</div>
      </div>
      <hr class="under-line">
    </article>

    <article >
      <div class="policy-items">
        <div>
          <input type="checkbox" id="check1" @change="[handleClickEachCheckBox(), btnActive()]" v-model="checkList1" />
          <label for="check1"></label>
        </div>
        <div class="policy-title-test">이용약관 동의<span class="necessary">(필수)</span></div>
        <div>
          <img @click="showDottoPolicyContent" class="side-menu-drop-btn filter-text" src="@/assets/icons/nav/filter-btn.svg" alt="sort" />
        </div>
      </div>
      <hr class="under-line">
      <div v-show="showDottoPolicy" class="policy-text" v-html="terms.dottoPolicyContent"></div>
    </article>

    <article >
      <div class="policy-items">
        <div>
          <input type="checkbox" id="check2" @change="[handleClickEachCheckBox(), btnActive()]" v-model="checkList2" />
          <label for="check2"></label>
        </div>
        <div class="policy-title-test">개인정보 수집 . 이용동<span class="necessary">(필수)</span></div>
        <div>
          <img @click="showPrivatePolicyContent" class="side-menu-drop-btn filter-text" src="@/assets/icons/nav/filter-btn.svg" alt="sort" />
        </div>
      </div>
      <hr class="under-line">
      <div v-show="showPrivatePolicy" class="policy-text" v-html="terms.privatePolicyContent"></div>
    </article>

    <section id="policy-btn-wrapper" >
      <button class="register-common-btn" type="button" @click="redirectLoginForm">이전</button>
      <button
          class="register-common-btn"
          type="button"
          @click="redirectRegisterForm"
          :disabled="openBtn"
          :class="openBtn ? '' : activeBtn"
      >가입</button>
    </section>

  </section>
</template>

<script lang="ts">
import { Component, Emit, Vue } from "vue-property-decorator";
import termsContent from '@/assets/dummy/terms.ts';

@Component
export default class PolicyComponent extends Vue {
  allCheckItems = false;
  checkList1 = false;
  checkList2 = false;
  checkList3 = false;

  showDottoPolicy = false;
  showPrivatePolicy = false;
  showMarketingPolicy = false;

  openBtn = true;
  activeBtn = 'register-common-btn-active';

  terms = {
    dottoPolicyContent: '',
    privatePolicyContent: '',
    marketingPolicyContent: '',
  }

  constructor() {
    super();
    this.terms = {
      dottoPolicyContent: termsContent[0].dottoPolicyContent,
      privatePolicyContent: termsContent[0].privatePolicyContent,
      marketingPolicyContent: termsContent[0].marketingPolicyContent
    }
  }

  created(): void {
    this.handleClickAllCheckBox();
  }

  private handleClickAllCheckBox() {
    if (this.allCheckItems) {
      this.checkList1 = true;
      this.checkList2 = true;
      this.checkList3 = true;
    } else {
      this.checkList1 = false;
      this.checkList2 = false;
      this.checkList3 = false;
    }
  }

  private btnActive() {
    this.openBtn = !(this.checkList1 && this.checkList2);
  }

  private handleClickEachCheckBox() {
    this.allCheckItems = this.checkList1 && this.checkList2 && this.checkList3;
  }

  private showDottoPolicyContent(): void {
    this.showDottoPolicy = !this.showDottoPolicy;
  }
  private showPrivatePolicyContent(): void {
    this.showPrivatePolicy = !this.showPrivatePolicy;
  }
  private showMarketingPolicyContent(): void {
  this.showMarketingPolicy = !this.showMarketingPolicy;
  }

  @Emit('changeComponent')
  private redirectRegisterForm(): string {
    if (!this.checkList1 || !this.checkList2) {
      alert('필수 선택사항을 체크해 주세요.');
      return 'PolicyComponent';
    } else {
      return 'RegisterComponent';
    }
  }

  @Emit('redirectLoginView')
  private redirectLoginForm(): string {
    return 'Login';
  }

}
</script>

<style scoped>
#policy-container {
  display: flex;
  overflow-y: auto;
  flex-direction: column;
  /*height: 100%;*/
  margin-top: 100px;
}
#policy-container section {
  margin-bottom: 0.6em;
}
#policy-btn-wrapper {
  /*display: flex;*/
  justify-content: space-around;
}
#policy-title {
  text-align: left;
  font-size: 15px;
  font-weight: 600;
}
.policy-title-test {
  margin-left: 10px;
}
.policy-items {
  display: flex;
  justify-content: flex-start;
  align-items: flex-end;
  margin-left: 27px;
}
.policy-items div:nth-child(1) {
  font-size: 14px;
  font-weight: 600;
}

.policy-text {
  text-align: left;
  border: 1px solid #eeeeee;
  height: 100px;
  overflow-y: auto;
  background: #efefef;
  font-size: 12px;
}

.necessary {
  color: #229d17;
  font-size: 12px;
}
.choice {
  color: #949494;
  font-size: 12px;
}
input {
  display: none;
}
input + label {
  display: inline-block;
  width: 20px;
  height: 20px;
  border: 2px solid #dedede;
  cursor: pointer;
  border-radius: 45px;
}
input + label::after {
  content: '✓';
  font-weight: 600;
  color: #dedede;
  font-size: 12px;
  position: relative;
  left: 1px;
  bottom: 5px;
}
input:checked + label::after {
  content: '✓';
  font-weight: 1000;
  color: #1dbe0f;
  font-size: 13px;
  position: relative;
  bottom: 5px;
}
input:checked + label {
  border: 2px solid #1dbe0f;
}

.under-line {
  width: 430px;
  margin-left: 27px;
}

.side-menu-drop-btn-01 {
  width: 18px;
  height: 10px;
  margin-left: 250px;
}

.side-menu-drop-btn-02 {
  width: 18px;
  height: 10px;
  margin-left: 194px;
}
</style>

파일명
LoginView.vue

<template>
  <main id="loginPage-container">
    <section id="logo-img" class="login-info-section">
      <span class="logo"><img src="@/assets/img/dotto.svg" alt="logo" /></span>
    </section>

    <section class="login-info-section">
      <form @submit.prevent="login">
        <div>
          <input @focus="clearMsg" class="login-info" type="text" v-model="id" placeholder="아이디" />
        </div>
        <div>
          <input @focus="clearMsg" class="login-info" autocomplete="off" type="password" v-model="password" placeholder="비밀번호" />
        </div>
        <div id="warning-msg" class="text-center">{{ loginFailed }}</div>
        <div id="auto-login-wrapper">
          <input type="checkbox" id="auto" @change="saveId" v-model="save">
          <label for="auto"></label> <span id="auto-login">아이디 저장</span>
        </div>
        <div>
          <button id="login-btn" type="submit">로그인</button>
        </div>
      </form>
    </section>

    <br />

    <section class="login-info-section">
      <div id="social-login" src="@/assets/icons/board/mymenu/loginSimpleLine.svg">ㅡㅡㅡㅡㅡㅡㅡㅡㅡ간편 로그인ㅡㅡㅡㅡㅡㅡㅡㅡㅡ</div>

        <div id="login-btn-img">

          <div class="google-btn-section">
            <button id="google-btn" class="social-btn-01">
              <img src="@/assets/img/login/Google.png" alt="google" />
            </button>
          </div>

          <div class="kakao-btn-section">
            <button id="kakao-btn" class="social-btn-02">
              <img src="@/assets/img/login/kakao.png" @click="kakaoLogin" alt="kakao" />
            </button>
          </div>

        </div>

    </section>

    <br />

    <section>
      <div id="register-box">

          <div id="lost-password" class="password-section">

            <router-link class="login-router forgot-user-info" to="#"><small>비밀번호 찾기</small></router-link>
          </div>
          <div id="join">

            <div id="register" class="join-section">
              <button class="login-router" @click="showRegisterView"><small>회원가입 하기</small></button>
            </div>
          </div>

      </div>
    </section>
  </main>
</template>

<script lang="ts">
import { Vue, Component, Emit } from "vue-property-decorator";
import { IUser } from "@/interfaces/IUser";

@Component({
  components: {
  }
})
export default class LoginView extends Vue {
  id = '';
  password = '';
  save = false;
  loginFailedMsg = '';
  modalTypeRegister = '';
  // $gAuth: any;

  params = {
    client_id: process.env.VUE_APP_GOOGLE_KEY
  }

  constructor() {
    super();
  }

  created(): void {
    this.getCookie();
  }

  async login(): Promise<void> {
    const sendData: IUser.ILoginProp = {
      id: this.id,
      password: this.password
    };
    const { data } = await this.axios.post('/sign-in', sendData) as { data: IUser.ILoginSuccess }
    const { success } = data;
    if (success) {
      if (this.save) this.saveId();
      this.saveState(data);
      await this.$router.push({
        path: '/dotto'
      });
    } else {
      this.loginFailed = '이메일 및 패스워드를 확인해주세요.';
    }
  }

  saveId(): void{
    if(this.save) {
      this.$cookies.set('idCookie', this.id,'30d');
    } else {
      this.$cookies.remove('idCookie');
      this.id = '';
    }
  }

  getCookie(): void {
    if (this.$cookies.isKey('idCookie')){
      this.id = this.$cookies.get('idCookie');
      this.save = true;
    }
  }

  saveState(userData: IUser.ILoginSuccess): void {
    this.$store.commit('userStore/login', userData);
  }

  clearMsg(): void {
    this.loginFailed = '';
  }

  private kakaoLogin(): void {
    window.Kakao.init(process.env.VUE_APP_KAKAO_KEY);

    if (window.Kakao.Auth.getAccessToken()) {
      window.Kakao.API.request({
        url: '/v1/user/unlink',
        success: function (response: Response) {
          console.log(response)
        },
        fail: function (error: Error) {
          console.log(error)
        },
      })
      window.Kakao.Auth.setAccessToken(undefined)
      window.Kakao.Auth.login({
        success: () => {
          window.Kakao.API.request({
            url: '/v2/user/me',
            data: {
              property_keys: ["kakao_account.email"]
            },
            success: async (response: Response) => {
              console.log(response);
            },
            fail: (error: Error) => {
              console.log(error)
            },
          })
        },fail: (error: Error) => {
          console.log(error)
        }
      })
    }
  }

  @Emit('modalTypeRegister')
  private showRegisterView() {
    return this.modalTypeRegister = 'RegisterView';
  }

  private set loginFailed(msg) {
    this.loginFailedMsg = msg;
  }
  private get loginFailed() {
    return this.loginFailedMsg;
  }

}
</script>

<style scoped>
hr {
  width: 80%;
}

#loginPage-container {
  display: flex;
  max-width: 400px;
  margin: 45px auto 45px auto;
  flex-direction: column;
  align-items: center;
}

.login-info {
  background: #fafafa;
  outline: none;
  width: 100%;
  border: 1px solid #eeeeee;
  height: 30px;
  font-size: 11px;
  padding-left: 5px;
  margin-bottom: 10px;
  border-radius: 2px;
}

.login-info-section {
  width: 75%;
  margin: auto;
}

#logo-img {
  margin-bottom: 30px;
  text-align: center;
}

#logo-img img {
  width: 120px;
  margin-bottom: 10px;
}

input[type="checkbox"] {
  display: none;
}

input[type="checkbox"] + label{
  display: inline-block;
  width: 15px;
  height: 15px;
  border:1px solid #919191;
  position: relative;
}

input[id="auto"]:checked + label::after{
  content: '✓';
  color: #05152f;
  font-weight: 800;
  font-size: 12px;
  padding-bottom: 3px;
  width: 10px;
  text-align: center;
  position: absolute;
  left: 1px;
  top: -3px;
}

#auto-login {
  font-size: 9px;
  margin-left: 5px;
}
#auto-login-wrapper {
  display: flex;
  justify-content: flex-start;
  align-items: center;
  margin-bottom: 10px;
}

#login-btn {
  border: 1px solid gray;
  border-radius: 3px;
  color: white;
  font-size: 12px;
  padding: 5px;
  background: #222222;
  width: 100%;
}

#login-btn-img {
  display: flex;
  /*position: relative;*/
  left: -10px;
}

#login-btn:hover{
  background: #464646;
  color: #ffffff;
}
#login-btn-img > div {
  /*margin-left: 20px;*/
}
#register-box {
  display: flex;
  justify-content: space-evenly;
}

#register > a {
  margin-right: 10px;

}

.login-router, #social-login {
  color: #919191;
  font-size: 12px;
  text-decoration: none;

}
.login-router:hover {
  font-size: 13px;
  font-weight: bold;
  cursor: pointer;
  color: #565656;
}
.forgot-user-info {

}

#social-login {
  text-align: center;
  margin-bottom: 10px;
}

#simple-login-icons {
  display: flex;
  justify-content: center;
}

#login-btn-img > li {
  float: left;

}

.social-btn-01 {
  border: 1px solid #eeeeee;
  border-radius: 3px;
  width: 255px;
  height: 30px;
  padding: 1px 0;
}
.social-btn-02 {
  border: 1px solid #eeeeee;
  border-radius: 3px;
  width: 255px;
  height: 30px;
  margin-top: 40px;
  padding: 1px 0;
}
#google-btn {
  background: #F5F5F5;
  display: flex;
  align-items: center;
  justify-content: space-around;
}
#google-btn::after {
  content: '구글 계정으로 로그인';
  font-size: 7px;
  color: #888888;
  font-weight: 600;
}
#kakao-btn {
  background: #fddc3f;
  display: flex;
  align-items: center;
  justify-content: space-evenly;
}
#kakao-btn::after {
  content: '카카오 계정으로 로그인';
  font-size: 7px;
  color: #595959;
  font-weight: 600;
}
#login-btn-img > div > button > img {
  width: 25px;
  position: relative;
}
#lost-password, #join {
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 25px;
  width: 5em;
}
#lost-password > span,  #join > span {
  font-size: 12px;
}
#warning-msg {
  color: red;
  font-size: 6px;
}

.google-btn-section {
  width: 0px;
  height: 0px;
}

.kakao-btn-section {
  width: 0px;
  height: 0px;
}

.password-section {
  /*!important;*/
  margin-top: 70px;
  margin-left: 10px;
}

.join-section {
  margin-top: 136px;
  margin-left: 10px;
}

</style>

**Comment by DaHoon06** [comment]
이렇게 하면 뭐 어떡하라고 올린거야...??????

저거 봐서 뭐하라고
