### ISSUE TITLE
검색 api 

### ISSUE THREAD

**Issue by jaeeey01** [DaHoon06/Dotto#80]
검색시 회원 & 아티스트 닉네임  + 닷투게시판 제목 

 - [x] 검색 구현 api - postman 테스트 완료
 - [ ] 검색 범위 확장 - 닷투게시판 지역, 태그

**Comment by DaHoon06** [comment]
1. member 닉네임으로 검색
2. 닷투 게시판 제목으로 검색

2가지 방법으로 실행 했습니다.

**첫번째 방법 ( 닉네임 )** 으로 검색했을 경우 아무런 반응 없이 빈배열로 반환 돼요

![image](https://user-images.githubusercontent.com/76781436/186284882-f0981410-a8c7-4059-8349-67c05f97c9cc.png)

**두번째 방법 ( 닷투 게시판 제목 )** 으로 검색했을 경우에는 2가지 에러문구가 출력되는데,

![image](https://user-images.githubusercontent.com/76781436/186284912-ec3dbf76-f3d1-46ed-a9df-9ad41a3ae36e.png)

![image](https://user-images.githubusercontent.com/76781436/186284957-ca6b60d9-979a-443f-b75b-6678495eaaaf.png)

dispatcherServlet 에러는 아래와 같습니다.!! 테스트는 member1 계정으로 진행했는데, 혹시 테스트를 하실 때 어떤 방법으로 하셨나요??? 

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Infinite recursion (StackOverflowError); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion 
(StackOverflowError) (through reference chain: com.dotto.app.entity.member.Member$HibernateProxy$XIqZRUPX["roles"]-
>org.hibernate.collection.internal.PersistentSet[0]->com.dotto.app.entity.member.MemberRole["member"]->com.dotto.app.entity.member.Member$HibernateProxy$XIqZRUPX["roles"]->org.hibernate.collection.internal.PersistentSet[0]->com.dotto.app.entity.member.MemberRole["member"]->com.dotto.app.entity.member.Member$HibernateProxy$XIqZRUPX["roles"]->org.hibernate.collection.internal.PersistentSet[0]->com.dotto.app.entity.member.MemberRole["member"]->com.dotto.app.entity.member.Member$HibernateProxy$XIqZRUPX["roles"]->org.hibernate.collection.internal.PersistentSet[0]->com.dotto.app.entity.member.MemberRole["member"]->com.dotto.app.entity.member.Member$HibernateProxy$XIqZRUPX["roles"]->org.hibernate.collection.internal.PersistentSet[0]-
.
.
.
