### ISSUE TITLE
이용약관 동의 API 구성

### ISSUE THREAD

**Issue by jaeeey01** [DaHoon06/Dotto#81]
- [x] 이용약관 동의 요청 API

**Comment by DaHoon06** [comment]
이것 때문에 생각을 좀 해봤는데요 어... member entity에 이 2개 컬럼 추가를 하면 안되는 이유가 뭔지 알 수 있을까요,,,???

지금 구조 상으로 보면 클라이언트 단에서 회원 가입을 누를 경우 1. 약관 테이블에 정보 저장. 2. 저장된 정보 불러옴 (pk 때문)
3. 불러온 pk를 유저 정보에 넣어줌.  4. 최종적으로 회원 가입?? 이 방식인 거잖아요???

이렇게 따로 분리해서 관리하는 이유가 뭔지 궁금해서 질문 드립니다. 보통 이렇게 하는 건지

**Comment by jaeeey01** [comment]
테이블 구성 간 멤버 엔티티에 이용약관 동의을 분리한 이유
 1. 멤버 테이블의 구성 목적에 이용약관 동의 여부가 필요하다 판단하지 않음.
 1-1 멤버가 가져야 하는 최소한의 멤버 변수로만 테이블을 구성하는 것이 좋음
 1-2 멤버 엔티티에 둘 수도 있지만 멤버 CRUD시에 필요한 항목이 아니라고 판단함.
 1-3 현업시에.. 반드시 조회 해야할 컬럼이 아닌데 그런 컬럼이 하나가 더 있어서 데이터 조회가 느려지는 경우도 있음
      (물론 전재는 '현업', 데이터량이 많은경우 발생함)
 1-4 이용약관 동의 항목은 많이 쓰이는 항목이 아님.(최초 가입 동의시, 약관 개정시)
 2. 기업들을 보면 이용 약관 개정이 될 경우 다시 동의를 받는 경우가 있는데 개정시 히스토리를 남기기 위함.
