### ISSUE TITLE
follow list 불러오는거에 조건 추가해야 될 것 같습니다. 회원 <-> 아티스트

### ISSUE THREAD

**Issue by DaHoon06** [DaHoon06/Dotto#89]
![image](https://user-images.githubusercontent.com/76781436/185338950-951d5e4e-5ae6-453e-8a01-dac10da3009c.png)

type을 정해서 회원과 아티스트를 구별하는 조건을 추가해야 할 것 같습니다.

게시판 3종류에 관련하여 검색도 한번 확인해야 할 것 같아요.

**Comment by jaeeey01** [comment]
아직 검색조건 api 안만들었음.. 추후 구현예정..
